#build website:
stages:
  - build
  - deploy

cache:
  paths:
    - vendor/

#build:
#  stage: build
#  only:
#    - master
#  image: composer
#  script:
#    - composer install --no-dev --no-progress --prefer-dist
#    - php artisan config:cache
#
#deploy:
#  stage: deploy
#  only:
#    - master
#  image: node:alpine
#  before_script:
#    - npm i -g firebase-tools
#    - echo $PRODUCTION_ENV_IN_BASE64 | base64 -d >> .env
#    - cat .env
#  script:
#    - npm install -g serverless
#    - serverless deploy
#    - serverless invoke --function artisan --data "php artisan config:clear"
#    - serverless invoke --function artisan --data "php artisan dump-autoload"

pulling from gitlab:
  stage: build
  only:
    - master
  image: composer
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$PRODUCTION_SSH_PRIVATE_KEY" | base64 --decode | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PRODUCTION_VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
#    - composer update
    - ssh $(echo $PRODUCTION_SSH_USER | base64 --decode)@$PRODUCTION_VM_IPADDRESS "hostname && /var/www/scripts/gitlab-ci.sh"
