#build website:
stages:
  - build
  - deploy

cache:
  paths:
    - vendor/

build:
  stage: build
  image: composer
  script:
    - composer install --no-dev --no-progress --prefer-dist

deploy:
  stage: deploy
  image: node:alpine
  script:
    - npm install -g serverless
    - serverless deploy -v
#
#stages:
#  - deploy
#
#deploy website:
#  stage: deploy
#  image:
#    name: amazon/aws-cli:2.10.3
#    entrypoint: [""]
#  script:
#    - aws --version
#    - echo "Hello S3" > test.txt
#    - aws s3 cp test.txt s3://$AWS_S3_BUCKET/testing
#
